#!/bin/bash

SYSTEM_BUNDLE_PATH="/Library/Containers/private.irc.irc/Data/Library/Application Support/IRC IRC/Extensions/"
SYSTEM_SCRIPT_PATH="/Library/Application Scripts/private.irc.irc/"

USER_BUNDLE_PATH="$HOME/Library/Containers/private.irc.irc/Data/Library/Application Support/IRC IRC/Extensions/"
USER_SCRIPT_PATH="$HOME/Library/Application Scripts/private.irc.irc/"

mkdir -p "${USER_BUNDLE_PATH}"
mkdir -p "${USER_SCRIPT_PATH}"

OLD_WIKILINKPARSER_PATH="${USER_BUNDLE_PATH}/WikipediaLinkParser.bundle"

if [ -d "${OLD_WIKILINKPARSER_PATH}" ]; then
	rm -rf "${OLD_WIKILINKPARSER_PATH}"
fi

cd "${SYSTEM_BUNDLE_PATH}"

chown -R $USER .
chgrp -R staff .

BUNDLES=`find . -name "*.bundle"`

for BUNDLE in $BUNDLES; do
	BUNDLE_PATH="${USER_BUNDLE_PATH}/${BUNDLE}"
	
	if [ -d "${BUNDLE_PATH}" ]; then
		rm -rf "${BUNDLE_PATH}"
	fi
	
	mv "${BUNDLE}" "${BUNDLE_PATH}"
done

cd "${SYSTEM_SCRIPT_PATH}"

chown -R $USER .
chgrp -R staff .

SCRIPT_EXTENSIONS="php scpt"

for EXTENSION in $SCRIPT_EXTENSIONS; do
	SCRIPTS=`find . -name "*.${EXTENSION}"`
	
	for SCRIPT in $SCRIPTS; do
		SCRIPT_PATH="${USER_SCRIPT_PATH}/${SCRIPT}"
		
		if [ -f "${SCRIPT_PATH}" ]; then
			rm "${SCRIPT_PATH}"
		fi
		
		mv "${SCRIPT}" "${SCRIPT_PATH}"
	done
done

exit
